apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: test-namespace
type: Opaque
stringData:
  DB_USER: admin
  DB_PASSWORD: s3cr3tP@ss
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
  namespace: test-namespace
spec:
  containers:
  - name: db-client
    image: busybox
    command: 
        - sh
        - -c
        - "echo App: $APP_NAME Env: $APP_ENV Level: $LOG_LEVEL && sleep 3600"
    resources:
      requests:
        memory: "10Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    envFrom:
      - secretRef:
          name: db-secret
