apiVersion: v1
kind: Pod

metadata:
  name: pod-configmap
  namespace: test-namespace

spec:
  containers:
    - name: app
      image: busybox
      command:
        - sh
        - -c
        - "echo App: $APP_NAME Env: $APP_ENV Level: $LOG_LEVEL && sleep 3600"

      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "250m"
          memory: "126Mi"

      envFrom:
        - configMapRef:
            name: app-configmap